### ISSUE TITLE
Should filter out empty rows during annotation

### ISSUE THREAD

**Issue by denklewer** [aladyeva-wustl/docker_linseed_snakemake#4]
If we will try to create an object from GSE file:
```
lo2 <- SinkhornNNLSLinseed$new(dataset = "GSE19830", 
                                   path = TMP.DIR,
                                   analysis_name = "GSE19830",
                                   cell_types = 3,
                                   coef_hinge_H = 1,
                                   coef_hinge_W = 1,
                                   coef_pos_D_h = 2,
                                   coef_pos_D_w = 2,
                                   coef_der_X = 1.0e-03,
                                   coef_der_Omega = 1.0e-03,
                                   global_iterations = 100,
                                   linearize = TRUE,
                               annotate = TRUE
                                   )
filtered <-  lo2$filtered_dataset
```
We will see that there is a row with empty name in the data:

![image](https://user-images.githubusercontent.com/19429157/220986715-a5acfcba-5a76-413d-b047-9e0314acbc0a.png)

This is because in fData for original GSE we have probes with no matching gene: 

![image](https://user-images.githubusercontent.com/19429157/220987269-168d0b3c-3c1f-43ad-b932-1aa6c48b174f.png)

And they are collapsed into  this single row.
Even more we will get an error during filtering:

![image](https://user-images.githubusercontent.com/19429157/220987763-7a6125c3-44a2-4ca9-a1ae-6f0123dff9d7.png)

**Comment by aladyeva-wustl** [comment]
Thank you!
@denklewer you can use an automatic branch to fix a bag
